site_name: MolExp
site_description: A flexible experiment management and workflow orchestration framework for molecular sciences
site_url: https://github.com/MolCrafts/molexp
repo_url: https://github.com/MolCrafts/molexp
repo_name: MolCrafts/molexp

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - content.code.copy
    - content.code.annotate

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting_started/installation.md
    - Quick Start: getting_started/quick_start.md
    - Basic Concepts: getting_started/concepts.md
  - User Guide:
    - Tasks: user_guide/tasks.md
    - Experiments: user_guide/experiments.md
    - Workflow Execution: user_guide/workflows.md
    - Parameter Studies: user_guide/parameters.md
  - Examples:
    - Basic Usage: examples/basic_usage.md
    - Experiment Management: examples/experiment_management.md
    - Shell Tasks: examples/shell_tasks.md
    - Parameter Exploration: examples/parameter_exploration.md
    - Advanced Workflows: examples/advanced_workflows.md
    - Hamilton Integration: examples/hamilton_integration.md
  - API Reference:
    - Task Classes: api/tasks.md
    - Task Management: api/pool_graph.md
    - Execution Engine: api/execution.md
    - Experiments: api/experiments.md
    - Parameters: api/parameters.md
  - Development:
    - Contributing: development/contributing.md
    - Testing: development/testing.md
    - Architecture: development/architecture.md

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - admonition
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
            show_source: true
            show_root_heading: true
            show_root_full_path: false
            merge_init_into_class: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/MolCrafts/molexp
  version:
    provider: mike