"""FileSystem abstraction — the workspace layer speaks this, never raw pathlib.

Two implementations: LocalFileSystem (wraps pathlib/os/shutil) and
RemoteFileSystem (wraps molq Transport + shell commands for missing ops).

All path arguments are strings interpreted relative to this filesystem.
"""

from __future__ import annotations

from collections.abc import Iterable
from dataclasses import dataclass
from typing import IO, Any, Protocol, runtime_checkable


@dataclass(frozen=True)
class StatResult:
    """Cross-platform stat result. Fields match the subset workspace needs."""

    size: int
    mtime: float
    is_dir: bool
    is_file: bool


@runtime_checkable
class FileSystem(Protocol):
    """Where files and directories actually live.

    Implementations: LocalFileSystem (stdlib), RemoteFileSystem (SSH via molq Transport).
    Third-party plugins may implement this Protocol without importing workspace internals.
    """

    # ── Path operations ──────────────────────────────────────────────────

    def join(self, *parts: str) -> str: ...
    def dirname(self, path: str) -> str: ...
    def basename(self, path: str) -> str: ...
    def resolve(self, path: str) -> str: ...
    def is_absolute(self, path: str) -> bool: ...

    # ── Existence / type ─────────────────────────────────────────────────

    def exists(self, path: str) -> bool: ...
    def is_dir(self, path: str) -> bool: ...
    def is_file(self, path: str) -> bool: ...

    # ── Directory operations ─────────────────────────────────────────────

    def mkdir(self, path: str, *, parents: bool = True, exist_ok: bool = True) -> None: ...
    def listdir(self, path: str) -> list[str]: ...
    def glob(self, path: str, pattern: str) -> Iterable[str]: ...
    def rglob(self, path: str, pattern: str) -> Iterable[str]: ...

    # ── Read ─────────────────────────────────────────────────────────────

    def read_text(self, path: str, encoding: str = "utf-8") -> str: ...
    def read_bytes(self, path: str) -> bytes: ...
    def open(self, path: str, mode: str = "r", encoding: str = "utf-8") -> IO[Any]: ...

    # ── Write ────────────────────────────────────────────────────────────

    def write_text(self, path: str, content: str, *, mode: int = 0o600) -> None: ...
    def write_bytes(self, path: str, content: bytes, *, mode: int = 0o600) -> None: ...

    # ── Mutations ────────────────────────────────────────────────────────

    def rename(self, src: str, dst: str) -> None: ...
    def remove(self, path: str, *, recursive: bool = False) -> None: ...
    def copy(self, src: str, dst: str) -> None: ...
    def copytree(self, src: str, dst: str, *, dirs_exist_ok: bool = False) -> None: ...

    # ── Metadata ─────────────────────────────────────────────────────────

    def stat(self, path: str) -> StatResult: ...
    def lstat(self, path: str) -> StatResult: ...
    def touch(self, path: str) -> None: ...
    def chmod(self, path: str, mode: int) -> None: ...
    def getsize(self, path: str) -> int: ...

    # ── Symlinks ─────────────────────────────────────────────────────────

    def symlink(self, src: str, dst: str) -> None: ...

    # ── Atomic I/O ───────────────────────────────────────────────────────

    def atomic_write_json(self, path: str, data: object) -> None: ...
    def atomic_write_text(self, path: str, content: str, *, encoding: str = "utf-8") -> None: ...
