"""molexp.harness — lineage-first scientific workflow harness.

Top-level package, sibling of :mod:`molexp.workspace`, :mod:`molexp.workflow`,
and :mod:`molexp.agent`. Owns state, artifact lineage, validation, approval,
execution, and audit for harness-driven runs; agents are demoted to
proposal generators behind hard boundaries defined in
``.claude/notes/harness-goal.md``.

Provenance split (one owner per concern): the harness records
**pipeline-artifact lineage only** — which stage of which run produced which
artifact, derived from which prior artifact (:class:`ArtifactLineageStore`)
— plus the audit event timeline. **Run-level provenance** (params, merged
config + ``config_hash``, profile, workflow identity, execution history,
environment) is owned by :mod:`molexp.workspace` (``RunMetadata`` /
``AssetCatalog``); code-version and environment capture belong there, never
here.

The state substrate: typed artifact references, an append-only event log, an
artifact-lineage edge store, and a Stage / StageRunner wrapper that brackets
each execution unit with events + lineage edges; on top sit WorkflowIR,
BoundWorkflow, CapabilityRegistry, TestSpec, executors, approval gates,
replay, and the ``molexp plan`` CLI path.

Dependency direction: ``molexp.harness → molexp.workspace`` plus a single
sanctioned edge ``molexp.harness → molexp.agent.router`` (the SDK-free
Protocol module — see spec ``harness-as-mode-substrate-03a``).
Imports from ``molexp.workflow``, ``molexp.plugins``, ``molexp.server``,
``molexp.cli``, or ``molexp.sweep`` are forbidden, and ``pydantic_ai`` /
``pydantic_graph`` must not be transitively pulled in — see
``tests/test_harness/test_import_guard.py``.
"""

from __future__ import annotations

from molexp.harness.audit import (
    find_last_successful_stage,
    generate_audit_report,
    replay_metadata,
)
from molexp.harness.capability import resolve_callable
from molexp.harness.core import HarnessRunContext, Stage, StageRunner
from molexp.harness.errors import (
    AgentResponseNotRegisteredError,
    ArtifactNotFoundError,
    CapabilityAlreadyRegisteredError,
    CapabilityCallValidationError,
    CapabilityNotFoundError,
    CapabilityResolutionError,
    EventSeqConflictError,
    HarnessError,
    StageExecutionError,
    StagePersistedFailureError,
)
from molexp.harness.executors import DryRunExecutor, Executor, LocalExecutor
from molexp.harness.gateways import AgentGateway, RouterBackedAgentGateway
from molexp.harness.mode import Mode
from molexp.harness.modes import PlanMode
from molexp.harness.policy import (
    ApprovalEventRecorder,
    ApprovalPolicyEvaluator,
    enforce_side_effect_approvals,
    make_side_effect_approval_requests,
)
from molexp.harness.registry import CapabilityRegistry, InMemoryCapabilityRegistry
from molexp.harness.schemas import (
    WELL_KNOWN_ARTIFACT_KINDS,
    AgentCallResult,
    AgentCallSpec,
    ApprovalDecision,
    ApprovalIntent,
    ApprovalPolicy,
    ApprovalRequest,
    ArtifactKind,
    ArtifactRef,
    AuditReport,
    BoundTask,
    BoundWorkflow,
    CapabilityInvocationResult,
    CommandResult,
    CommandSpec,
    DependencyEdge,
    EventType,
    ExecutionEnvironment,
    ExecutionReport,
    ExecutionResult,
    ExpectedOutput,
    ExperimentReport,
    ExperimentSpec,
    FinalReport,
    HarnessEvent,
    InputSet,
    ModeResult,
    ParameterSource,
    ParameterValue,
    PathPolicy,
    PlanReview,
    PlanReviewFinding,
    ResolvedQuestion,
    ResourcePolicy,
    SpecCondition,
    SpecVariable,
    SweepAxis,
    SweepStrategy,
    TaskIR,
    TestKind,
    TestResult,
    TestSource,
    TestSpec,
    TestSpecBundle,
    TestStatus,
    ToolCapability,
    ToolPolicy,
    UserPlan,
    ValidationReport,
    ValidationViolation,
    WorkflowIR,
    WorkflowSource,
)
from molexp.harness.stages import (
    ApprovalGate,
    Approver,
    BindMolcraftsTasks,
    CompileWorkflow,
    ExecuteTests,
    ExecuteWorkflow,
    ExtractWorkflowIR,
    GenerateAuditReport,
    GenerateExecutionReport,
    GenerateExperimentReport,
    GenerateExperimentSpec,
    GenerateFinalReport,
    GenerateInputSet,
    GenerateTestCode,
    GenerateTestSpec,
    GenerateWorkflowSource,
    InvokeCapability,
    MaterializeExecution,
    RepairLoop,
    ResolveCapabilities,
    ReviewPlan,
    SaveUserPlan,
    ValidateBoundWorkflow,
    ValidateExperimentSpec,
    ValidateInputSet,
    ValidateTestSource,
    ValidateTestSpec,
    ValidateWorkflowIR,
    ValidateWorkflowSource,
    auto_grant_approver,
)
from molexp.harness.store import (
    ArtifactLineageStore,
    ArtifactStore,
    EventLog,
    FileArtifactStore,
    SQLiteArtifactLineageStore,
    SQLiteEventLog,
)
from molexp.harness.validators import (
    BoundWorkflowValidator,
    ExperimentSpecValidator,
    InputSetValidator,
    ProvenanceValidator,
    TestSourceValidator,
    TestSpecValidator,
    WorkflowIRValidator,
    WorkflowSourceValidator,
)

__all__ = [
    "WELL_KNOWN_ARTIFACT_KINDS",
    "AgentCallResult",
    "AgentCallSpec",
    "AgentGateway",
    "AgentResponseNotRegisteredError",
    "ApprovalDecision",
    "ApprovalEventRecorder",
    "ApprovalGate",
    "ApprovalIntent",
    "ApprovalPolicy",
    "ApprovalPolicyEvaluator",
    "ApprovalRequest",
    "Approver",
    "ArtifactKind",
    "ArtifactLineageStore",
    "ArtifactNotFoundError",
    "ArtifactRef",
    "ArtifactStore",
    "AuditReport",
    "BindMolcraftsTasks",
    "BoundTask",
    "BoundWorkflow",
    "BoundWorkflowValidator",
    "CapabilityAlreadyRegisteredError",
    "CapabilityCallValidationError",
    "CapabilityInvocationResult",
    "CapabilityNotFoundError",
    "CapabilityRegistry",
    "CapabilityResolutionError",
    "CommandResult",
    "CommandSpec",
    "CompileWorkflow",
    "DependencyEdge",
    "DryRunExecutor",
    "EventLog",
    "EventSeqConflictError",
    "EventType",
    "ExecuteTests",
    "ExecuteWorkflow",
    "ExecutionEnvironment",
    "ExecutionReport",
    "ExecutionResult",
    "Executor",
    "ExpectedOutput",
    "ExperimentReport",
    "ExperimentSpec",
    "ExperimentSpecValidator",
    "ExtractWorkflowIR",
    "FileArtifactStore",
    "FinalReport",
    "GenerateAuditReport",
    "GenerateExecutionReport",
    "GenerateExperimentReport",
    "GenerateExperimentSpec",
    "GenerateFinalReport",
    "GenerateInputSet",
    "GenerateTestCode",
    "GenerateTestSpec",
    "GenerateWorkflowSource",
    "HarnessError",
    "HarnessEvent",
    "HarnessRunContext",
    "InMemoryCapabilityRegistry",
    "InputSet",
    "InputSetValidator",
    "InvokeCapability",
    "LocalExecutor",
    "MaterializeExecution",
    "Mode",
    "ModeResult",
    "ParameterSource",
    "ParameterValue",
    "PathPolicy",
    "PlanMode",
    "PlanReview",
    "PlanReviewFinding",
    "ProvenanceValidator",
    "RepairLoop",
    "ResolveCapabilities",
    "ResolvedQuestion",
    "ResourcePolicy",
    "ReviewPlan",
    "RouterBackedAgentGateway",
    "SQLiteArtifactLineageStore",
    "SQLiteEventLog",
    "SaveUserPlan",
    "SpecCondition",
    "SpecVariable",
    "Stage",
    "StageExecutionError",
    "StagePersistedFailureError",
    "StageRunner",
    "SweepAxis",
    "SweepStrategy",
    "TaskIR",
    "TestKind",
    "TestResult",
    "TestSource",
    "TestSourceValidator",
    "TestSpec",
    "TestSpecBundle",
    "TestSpecValidator",
    "TestStatus",
    "ToolCapability",
    "ToolPolicy",
    "UserPlan",
    "ValidateBoundWorkflow",
    "ValidateExperimentSpec",
    "ValidateInputSet",
    "ValidateTestSource",
    "ValidateTestSpec",
    "ValidateWorkflowIR",
    "ValidateWorkflowSource",
    "ValidationReport",
    "ValidationViolation",
    "WorkflowIR",
    "WorkflowIRValidator",
    "WorkflowSource",
    "WorkflowSourceValidator",
    "auto_grant_approver",
    "enforce_side_effect_approvals",
    "find_last_successful_stage",
    "generate_audit_report",
    "make_side_effect_approval_requests",
    "replay_metadata",
    "resolve_callable",
]
