"""``AuditReport`` — final audit-trail artifact (Phase 10 §12.2).

Frozen pydantic. Generated by
:func:`molexp.harness.audit.generate.generate_audit_report` from the
event log + artifact store + provenance store after a run completes.

The report is the answer to "what happened in this run?" — every
approval, every validation, every failure, every command, every artifact
boundary. The harness goal is that this report can fully reconstruct an
audit trail without needing to re-read the source code or the LLM logs.
"""

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, ConfigDict, Field

__all__ = ["AuditReport"]


class AuditReport(BaseModel):
    """Audit-trail summary of one harness run."""

    model_config = ConfigDict(frozen=True)

    run_id: str
    summary: str
    root_artifact_id: str | None = None
    final_artifact_ids: list[str] = Field(default_factory=list)
    approvals: list[dict[str, Any]] = Field(default_factory=list)
    validation_results: list[str] = Field(default_factory=list)
    failures: list[dict[str, Any]] = Field(default_factory=list)
    command_summaries: list[dict[str, Any]] = Field(default_factory=list)
    limitations: list[str] = Field(default_factory=list)
