"""``MaterializeExecution`` — write the generated programs + driver to disk.

Pure stage (no LLM, no subprocess): reads the validated ``workflow_source``,
``test_source``, and ``workflow_ir`` artifacts and materializes three files
under ``<run_dir>/generated/`` — the workflow module, the pytest module, and
a deterministic ``run_workflow.py`` driver rendered from
:data:`_DRIVER_TEMPLATE`. Each file is registered as a kind-``input_file``
artifact with lineage back to the artifact it came from; the stage returns
the **driver's** ref (single-ref contract).

Import-guard note: the driver imports ``molexp`` / ``WorkflowRuntime`` *as
subprocess source text only* — this module itself must never import
``molexp.workflow`` (not even lazily). The template is a plain string; the
engine loads in the executor's child process, never in the harness process.

Sentinel rendering uses ``str.replace`` on ``__MODULE_NAME__`` /
``__PARAMS_JSON__`` (not ``str.format``) so the template needs no
brace-escaping. The params payload is ``{name: ParameterValue.value}`` from
``WorkflowIR.inputs``, embedded as canonical ``json.dumps(..., sort_keys=True)``.
"""

from __future__ import annotations

import json
from typing import ClassVar, TypeVar

from pydantic import BaseModel

from molexp.harness.core.run_context import HarnessRunContext
from molexp.harness.core.stage import Stage
from molexp.harness.errors import StageExecutionError
from molexp.harness.schemas import ArtifactRef, TestSource, WorkflowIR, WorkflowSource
from molexp.harness.stages._resolve import require_latest

__all__ = ["MaterializeExecution"]

_M = TypeVar("_M", bound=BaseModel)

_DRIVER_TEMPLATE = '''\
"""Auto-generated by molexp harness MaterializeExecution -- do not edit."""

import asyncio
import json
import sys

from molexp import WorkflowRuntime

from __MODULE_NAME__ import build_workflow

PARAMS = json.loads(r"""__PARAMS_JSON__""")


def main() -> int:
    compiled = build_workflow().compile()
    result = asyncio.run(WorkflowRuntime().execute(compiled, config=PARAMS or None))
    with open("outputs.json", "w", encoding="utf-8") as fh:
        json.dump(result.outputs, fh, default=str)
    return 0 if result.status == "completed" else 1


if __name__ == "__main__":
    sys.exit(main())
'''


class MaterializeExecution(Stage):
    """Materialize workflow module, test module, and driver under run_dir/generated."""

    name: ClassVar[str] = "materialize_execution"

    async def run(self, ctx: HarnessRunContext) -> ArtifactRef:
        ws_ref = require_latest(ctx, "workflow_source", stage=self.name)
        ts_ref = require_latest(ctx, "test_source", stage=self.name)
        ir_ref = require_latest(ctx, "workflow_ir", stage=self.name)

        ws = self._parse(ctx, ws_ref.id, WorkflowSource, "workflow_source")
        ts = self._parse(ctx, ts_ref.id, TestSource, "test_source")
        ir = self._parse(ctx, ir_ref.id, WorkflowIR, "workflow_ir")

        generated = ctx.workspace_root / "generated"
        generated.mkdir(parents=True, exist_ok=True)

        workflow_path = generated / f"{ws.module_name}.py"
        workflow_path.write_text(ws.source, encoding="utf-8")
        test_path = generated / f"{ts.module_name}.py"
        test_path.write_text(ts.source, encoding="utf-8")

        params = {name: pv.value for name, pv in ir.inputs.items()}
        driver_text = _DRIVER_TEMPLATE.replace("__MODULE_NAME__", ws.module_name).replace(
            "__PARAMS_JSON__", json.dumps(params, sort_keys=True)
        )
        driver_path = generated / "run_workflow.py"
        driver_path.write_text(driver_text, encoding="utf-8")

        ctx.artifact_store.put_file(
            kind="input_file",
            path=workflow_path,
            created_by="MaterializeExecution",
            parent_ids=[ws_ref.id],
        )
        ctx.artifact_store.put_file(
            kind="input_file",
            path=test_path,
            created_by="MaterializeExecution",
            parent_ids=[ts_ref.id],
        )
        return ctx.artifact_store.put_file(
            kind="input_file",
            path=driver_path,
            created_by="MaterializeExecution",
            parent_ids=[ws_ref.id, ir_ref.id, ts_ref.id],
        )

    def _parse(
        self,
        ctx: HarnessRunContext,
        artifact_id: str,
        model: type[_M],
        kind: str,
    ) -> _M:
        raw = ctx.artifact_store.get(artifact_id)
        try:
            return model.model_validate_json(raw)
        except Exception as exc:
            raise StageExecutionError(
                f"stage {self.name!r} could not parse the {kind!r} artifact "
                f"{artifact_id!r}: {exc!r}"
            ) from exc
